# Generated by Django 4.2.6 on 2023-10-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_schema__initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event_date',
        ),
    ]
