# Generated by Django 4.2.6 on 2023-10-16 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('attendees', '0002_remove_attendee_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='recurring_scheduled_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.recurringscheduledsession'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='session_date',
            field=models.DateField(null=True),
        ),
    ]
