# Generated by Django 4.2.6 on 2023-10-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_onetimescheduledsession'),
        ('attendees', '0003_attendee_recurring_scheduled_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='one_time_scheduled_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.onetimescheduledsession'),
        ),
    ]
