# Generated by Django 4.2.6 on 2023-10-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringScheduledSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day', models.IntegerField(choices=[(10, 'Monday'), (20, 'Tuesday'), (30, 'Wednesday'), (40, 'Thursday'), (50, 'Friday'), (60, 'Saturday'), (70, 'Sunday')])),
                ('time', models.TimeField()),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.scheduleconfiguration')),
            ],
        ),
    ]
