# Generated by Django 4.2.6 on 2023-10-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeScheduledSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.scheduleconfiguration')),
            ],
        ),
    ]
